import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "./aboutus.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next js website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.image}>
        <Image
          src="/page1icon/demo.jpg"
          width="1300"
          height="510"
          className={styles.demo}
        ></Image>
        <h1 className={styles.heading1}>THE Funfliz STORY</h1>
        <p className={styles.heading2}>
          Making Diagnostics Accessible to people
        </p>
      </div>

      <div className={styles.maindiv}>
        <div className={styles.side1}>
          <Image
            src="/page1icon/about.png"
            width="550"
            height="350"
            className={styles.image2}
          ></Image>
        </div>
        <div className={styles.side2}>
          <h1>How We Started</h1>
          <p className={styles.paragraph}>
            We started our journey in 2018 driven by a strong sense of <br />
            purpose & very important question in our minds How can <br />
            we make quality healthcare accessible to each and every <br />
            person across our diverse country.
          </p>
        </div>
      </div>
      <div className={styles.maindivpart2}>
        <div className={styles.side3}>
          <h1 className={styles.heading3}>Defining The Problem</h1>
          <p className={styles.paragraph2}>
            We witnessed stark realities both in urban and rural areas <br />
            right from the issue of affordability to the problem of <br />
            accessibility. This innate desire to improve overall well-being{" "}
            <br />
            of people by giving them accurate diagnostics, led to the <br />
            birth of Funfliz Labs.
          </p>
        </div>
        <div className={styles.side4}>
          <Image
            src="/page1icon/third.png"
            width="550"
            height="350"
            className={styles.image3}
          ></Image>
        </div>
      </div>

      <div className={styles.maindiv4}>
        <div className={styles.side4}>
          <Image
            src="/page1icon/forth.png"
            width="550"
            height="350"
            className={styles.image4}
          ></Image>
        </div>
        <div className={styles.side5}>
          <h1 className={styles.heading5}>
            Creating a Pan-India Dx revolution
          </h1>
          <p className={styles.paragraph4}>
            Entwined with the philosophy of making diagnostics, the first <br />
            step, towards preventive health & disease management, <br />
            weve been able to cater to 2.5 million Indians in a short <br />
            span of 4 years.
          </p>
        </div>
      </div>

      <div className={styles.image5}>
        <Image
          src="/page1icon/five.jpg"
          width="1300"
          height="510"
          className={styles.demo5}
        ></Image>
        <h1 className={styles.heading6}>THE Funfliz STORY</h1>
        <p className={styles.heading7}>
          At Redcliffe Labs, we’ve built a comprehensive portfolio approach both
          with <br /> routine and specialized test menus with advanced testing labs <br /> all
          over India. We cater to all diagnostic needs, thereby contributing to
          the <br /> health needs of millions of patients.
        </p>

        <div>
          <div className={styles.icon1}>
            {" "}
            <Image
              src="/page1icon/ICON1.png"
              width="80"
              height="80"
              className={styles.imageicon}
            ></Image>
          </div>
          <h1 className={styles.heading8}>
            Digital-first <br />
            approach{" "}
          </h1>
          <div className={styles.icon2}>
            {" "}
            <Image
              src="/page1icon/ICON2.png"
              width="80"
              height="80"
              className={styles.imageicon2}
            ></Image>
          </div>
          <h1 className={styles.heading9}>
            Accurate Reports <br />
            within 24 Hrs{" "}
          </h1>
          <div className={styles.icon3}>
            {" "}
            <Image
              src="/page1icon/ICON3.png"
              width="80"
              height="80"
              className={styles.imageicon3}
            ></Image>
          </div>
          <h1 className={styles.heading10}>
            On-demand 1-hour <br />
            home collection{" "}
          </h1>

          <div className={styles.handmain}>
            <div className={styles.hand1}>
              <Image
                src="/page1icon/five.png"
                height="200"
                width="200"
                className={styles.fiveimg}
              ></Image>
            </div>
            <div className={styles.hand2}>
              <h1 className={styles.hand2part1}>OUR VISION</h1>
              <p className={styles.hand2part2}>
                High Quality and Affordable Diagnostics Platform for <br />
                Bharat - Empowering Health, Impacting Lives.
              </p>

              <h1 className={styles.hand2part3}>OUR MISSION</h1>
              <p className={styles.hand2part4}>
                To serve <b> 500 million</b> Indians by 2030
              </p>
            </div>
          </div>

          <div className={styles.secondlastb}>
            <Image
              src="/page1icon/five.png"
              height="300"
              width="300"
              className={styles.siximg}
            ></Image>
            <h1 className={styles.sixheading}>OUR IMPACT DIFFERENTIATORS</h1>
            <div className={styles.siximg1}>
              <Image
                src="/page1icon/six12.png"
                height="20"
                width="40"
                className={styles.siximage}
              ></Image>
              <h1 className={styles.sixheading1}>Technology Integration</h1>
              <p className={styles.sixpra}>
                From tamper-proof sample <br />
                collection to accurate <br />
                reports, we deploy <br />
              </p>
            </div>
            <div className={styles.siximg2}>
              <Image
                src="/page1icon/six11.png"
                height="20"
                width="30"
                className={styles.siximg11}
              ></Image>
              <h1 className={styles.sixheading11}>Accessible to all</h1>
              <p className={styles.sixpra2}>
                Our focus is to make <br />
                diagnostics accessible <br />
                to everyone from cities
              </p>
            </div>
            <div className={styles.siximg3}>
              <Image
                src="/page1icon/six13.png"
                height="20"
                width="30"
                className={styles.siximg12}
              ></Image>
              <h1 className={styles.sixheading13}>Robust Interfaces</h1>
              <p className={styles.paragraph131}>
                Right from booking the test to <br />
                making reports available to <br />
                resolve other queries in no
              </p>
            </div>
          </div>
          <div className={styles.second2}>
            <h1 className={styles.second3}>Funfliz LABS QUALITY ASSURE</h1>
            <p className={styles.second4}>
              Our internal quality benchmarks ensure that accuracy is maintained
              at every step of testing of <br />
              samples. Right from the bag in which sample is transported to the
              six-sigma processes, these <br />
              quality standards are followed stringently to ensure test report
              accuracy and reliability of <br />
              highest standard.
            </p>
          </div>
        </div>

        <div className={styles.mainp}>
          <div className={styles.mainp1}>
            <div className={styles.p1rotat}>
              <Image
                src="/page1icon/p1.png"
                height="20"
                width="49"
                className={styles.p1img}
              ></Image>
            </div>
            <h1 className={styles.p1heading}>
              NABL Accredited & ISO Certified
            </h1>
            <p className={styles.p1paragraph}>
              All our labs, National & Regional <br />
              Reference are accredited by NABL. <br />
              We follow guidelines laid down by <br />
              the International Standard <br />
              ISO15189:2012.
            </p>
          </div>
          <div className={styles.mainp2}>
            <div className={styles.p1rotat}>
              <Image
                src="/page1icon/p2.png"
                height="20"
                width="49"
                className={styles.p1img}
              ></Image>
            </div>
            <h1 className={styles.p1heading}>
              Six-Sigma <br /> Processes
            </h1>
            <p className={styles.p1paragraph}>
              Two levels of quality control are <br /> performed at the peak
              hour <br />
              followed by one level every eight hours <br />
              The quality standards are integrated in all phases: pre- <br />
              analytical, analytical, and post- <br />
              analytical.
            </p>
          </div>
          <div className={styles.mainp3}>
            <div className={styles.p1rotat}>
              <Image
                src="/page1icon/p3.png"
                height="20"
                width="49"
                className={styles.p1img}
              ></Image>
            </div>
            <h1 className={styles.p1heading}>
              Innovative <br /> Patented <br /> Technology
            </h1>
            <p className={styles.p1paragraph}>
              Implementation of real-time <br />
              temperature monitoring technology <br />
              ensures sample integrity for <br />
              accurate test results.
            </p>
          </div>
        </div>
        <div className={styles.maincore}>
          <div className={styles.core1}>
            <Image
              src="/page1icon/happycustomer.png"
              height="50"
              width="50"
              className={styles.coreimg1}
            ></Image>
            <h1 className={styles.coreheading1}>CUSTOMER FIRST</h1>
          </div>
          <div className={styles.core2}>
            <Image
              src="/page1icon/quality.png"
              height="50"
              width="50"
              className={styles.coreimg1}
            ></Image>
            <h1 className={styles.coreheading2}>QUALITY</h1>
          </div>
          <div className={styles.core3}>
            <Image
              src="/page1icon/integrity.png"
              height="50"
              width="50"
              className={styles.coreimg1}
            ></Image>
            <h1 className={styles.coreheading2}>INTEGRITY</h1>
          </div>
          <div className={styles.core4}>
            <Image
              src="/page1icon/sustainability.png"
              height="50"
              width="50"
              className={styles.coreimg1}
            ></Image>
            <h1 className={styles.coreheading4}>SUSTAINABILITY</h1>
          </div>
          <div className={styles.core5}>
            <Image
              src="/page1icon/efficiency.png"
              height="50"
              width="50"
              className={styles.coreimg1}
            ></Image>
            <h1 className={styles.coreheading5}>EFFICIENCY</h1>
          </div>
          <div className={styles.core6}>
            <Image
              src="/page1icon/respect.png"
              height="50"
              width="50"
              className={styles.coreimg1}
            ></Image>
            <h1 className={styles.coreheading6}>RESPECT</h1>
          </div>
        </div>
      </div>
      <h1 className={styles.headingmain}>OUR CORE VALUES</h1>
    </>
  );
}
